# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYJsonVerifyExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YYJsonVerifyExample

  target 'YYJsonVerifyExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YYJsonVerifyExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
